module.exports = {
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_UPDATED: 'TRANSACTION_UPDATED',
  TRANSACTION_SUBMITTED: 'TRANSACTION_SUBMITTED',
  PROCESSINSTANCESTAGE_CREATED: 'PROCESSINSTANCESTAGE_CREATED',

  WORKFLOW_STARTED: 'WORKFLOW_STARTED',
  WORKFLOW_COMPLETED: 'WORKFLOW_COMPLETED',

  TASK_CREATED: 'TASK_CREATED',
  TASK_COMPLETED: 'TASK_COMPLETED',

  GENERATE_PDF: 'GENERATE_PDF'

}