'use strict'

/**
 * أكواد أحداث audit_logs — ثبات الأسماء أهم من الترجمة.
 * ممنوع وضع password / PIN / OTP / private_key / raw tokens في details.
 */
const AUDIT_ACTIONS = Object.freeze({
  REFRESH_TOKEN_REUSE: 'REFRESH_TOKEN_REUSE',
  LOGOUT: 'LOGOUT',
  ACCOUNT_ACCESS_BLOCKED: 'ACCOUNT_ACCESS_BLOCKED',

  EMPLOYEE_REGISTERED: 'EMPLOYEE_REGISTERED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',

  ROLE_PERMISSIONS_CREATED: 'ROLE_PERMISSIONS_CREATED',
  ROLE_PERMISSIONS_UPDATED: 'ROLE_PERMISSIONS_UPDATED',

  TRANSACTION_SUBMITTED: 'TRANSACTION_SUBMITTED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_REJECTED: 'TASK_REJECTED',
  TASK_PICKED_UP: 'TASK_PICKED_UP',
  TASK_RELEASED: 'TASK_RELEASED',

  FINAL_DOCUMENT_SAVED: 'FINAL_DOCUMENT_SAVED',
  FINAL_DOCUMENT_GENERATED: 'FINAL_DOCUMENT_GENERATED',

  PROCESS_CREATED: 'PROCESS_CREATED',
  PROCESS_REVIEWED: 'PROCESS_REVIEWED',
  PROCESS_STATUS_CHANGED: 'PROCESS_STATUS_CHANGED',

  ODR_CREATED: 'ODR_CREATED',
  ODR_STATUS_CHANGED: 'ODR_STATUS_CHANGED',
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_STATUS_CHANGED: 'DEPARTMENT_STATUS_CHANGED',

  DEVICE_TOKEN_REGISTERED: 'DEVICE_TOKEN_REGISTERED',
  CITIZEN_REGISTER_STARTED: 'CITIZEN_REGISTER_STARTED'
})

module.exports = {
  AUDIT_ACTIONS
}
